### ISSUE TITLE
Fix styling on groups gallery

### ISSUE THREAD

**Issue by smsm1** [cyclestreets/cyclescape#300]
http://www.cyclescape.org/groups

Needs something like 

``` css
article.group p a {
  word-wrap:break-word;
  word-break:break-all;
}
```
