### ISSUE TITLE
Date/time values are not translated

### ISSUE THREAD

**Issue by PetrDlouhy** [cyclestreets/cyclescape#751]
The date and time values across whole Cyclescape are mot translated. I solved that in the past by copying following code from Ruby source to locale. But it is not very clever way, because of the code duplication. Can this be get somehow directly from the Ruby source?

```
  helpers:
    page_entries_info:
      more_pages:
        display_entries: Zobrazení %{entry_name} <b>%{first}&nbsp;-&nbsp;%{last}</b> z <b>%{total}</b> celkem
      one_page:
        display_entries:
          one: Zobrazení <b>%{count}</b> %{entry_name}
          other: Zobrazení <b>všech %{count}</b> %{entry_name}
          zero: Žádné %{entry_name} nenalezeny
  views:
    pagination:
      first: "&laquo; První"
      last: Poslední &raquo;
      next: Další &rsaquo;
      previous: "&lsaquo; Předchozí"
      truncate: "&hellip;"
  date:
    abbr_day_names:
    - Ne
    - Po
    - Út
    - St
    - Čt
    - Pá
    - So
    abbr_month_names:
    -
    - led
    - úno
    - bře
    - dub
    - kvě
    - čvn
    - čvc
    - srp
    - zář
    - říj
    - lis
    - pro
    day_names:
    - neděle
    - pondělí
    - úterý
    - středa
    - čtvrtek
    - pátek
    - sobota
    formats:
      default: "%d. %m. %Y"
      long: "%d. %B %Y"
      short: "%d %b"
    month_names:
    -
    - leden
    - únor
    - březen
    - duben
    - květen
    - červen
    - červenec
    - srpen
    - září
    - říjen
    - listopad
    - prosinec
    order:
    - :day
    - :month
    - :year
  datetime:
    distance_in_words:
      about_x_hours:
        one: asi hodinou
        few: asi %{count} hodinami
        other: asi %{count} hodinami
      about_x_months:
        one: asi měsícem
        few: asi %{count} měsíci
        other: asi %{count} měsíci
      about_x_years:
        one: asi rokem
        few: asi %{count} roky
        other: asi %{count} roky
      almost_x_years:
        one: téměř rokem
        few: téměř %{count} roky
        other: téměř %{count} roky
      half_a_minute: půl minutou
      less_than_x_minutes:
        one: necelou minutou
        few: ani ne %{count} minutami
        other: ani ne %{count} minutami
      less_than_x_seconds:
        one: necelou sekundou
        few: ani ne %{count} sekundami
        other: ani ne %{count} sekundami
      over_x_years:
        one: více než rokem
        few: více než %{count} roky
        other: více než %{count} roky
      x_days:
        one: 24 hodinami
        few: "%{count} dny"
        other: "%{count} dny"
      x_minutes:
        one: minutou
        few: "%{count} minutami"
        other: "%{count} minutami"
      x_months:
        one: měsícem
        few: "%{count} měsíci"
        other: "%{count} měsíci"
      x_seconds:
        one: sekundou
        few: "%{count} sekundami"
        other: "%{count} sekundami"
    prompts:
      day: Den
      hour: Hodina
      minute: Minuta
      month: Měsíc
      second: Sekunda
      year: Rok
  errors:
    format: "%{attribute} %{message}"
    messages:
      accepted: musí být potvrzeno
      blank: je povinná položka
      present: musí být prázdný/á/é
      confirmation: nebylo potvrzeno
      empty: nesmí být prázdný/á/é
      equal_to: musí být rovno %{count}
      even: musí být sudé číslo
      exclusion: je vyhrazeno pro jiný účel
      greater_than: musí být větší než %{count}
      greater_than_or_equal_to: musí být větší nebo rovno %{count}
      inclusion: není v seznamu povolených hodnot
      invalid: není platná hodnota
      less_than: musí být méně než %{count}
      less_than_or_equal_to: musí být méně nebo rovno %{count}
      not_a_number: není číslo
      not_an_integer: musí být celé číslo
      odd: musí být liché číslo
      required: musí existovat
      taken: již databáze obsahuje
      too_long: je příliš dlouhý/á/é (max. %{count} znaků)
      too_short: je příliš krátký/á/é (min. %{count} znaků)
      wrong_length: nemá správnou délku (očekáváno %{count} znaků)
      other_than: musí být rozdílný/á/é od %{count}
    template:
      body: 'Následující pole obsahují chybně vyplněné údaje: '
      header:
        one: Při ukládání objektu %{model} došlo k chybám a nebylo jej možné uložit
        few: Při ukládání objektu %{model} došlo ke %{count} chybám a nebylo možné
          jej uložit
        other: Při ukládání objektu %{model} došlo ke %{count} chybám a nebylo možné
          jej uložit
  helpers:
    select:
      prompt: Prosím vyberte si
    submit:
      create: Vytvořit %{model}
      submit: Uložit %{model}
      update: Aktualizovat %{model}
  number:
    currency:
      format:
        delimiter: " "
        format: "%n %u"
        precision: 2
        separator: ","
        significant: false
        strip_insignificant_zeros: false
        unit: Kč
    format:
      delimiter: "."
      precision: 3
      separator: ","
      significant: false
      strip_insignificant_zeros: false
    human:
      decimal_units:
        format: "%n %u"
        units:
          billion: Miliarda
          million: Milion
          quadrillion: Kvadrilion
          thousand: Tisíc
          trillion: Bilion
          unit: ''
      format:
        delimiter: ''
        precision: 1
        significant: false
        strip_insignificant_zeros: false
      storage_units:
        format: "%n %u"
        units:
          byte: B
          gb: GB
          kb: KB
          mb: MB
          tb: TB
    percentage:
      format:
        delimiter: ''
        format: "%n%"
    precision:
      format:
        delimiter: ''
  support:
    array:
      last_word_connector: " a "
      two_words_connector: " a "
      words_connector: ", "
  time:
    am: am
    formats:
      default: "%a %d. %B %Y %H:%M %z"
      long: "%A %d. %B %Y %H:%M"
      short: "%d. %m. %H:%M"
    pm: pm
```
